site_name: "Alisa Chikomazova | Portfolio"

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - python
  locale: en 

site_url: https://alisa-chiko.github.io/  
extra_css:
  - stylesheets/extra.css  
nav:
  - Welcome: index.md
  - Projects:
      - Overview: labs.md
      - Lab 1: labs/lab_1.md
      - Lab 2: labs/lab_2.md
      - Lab 3: labs/lab_3.md
      - Lab 4: labs/lab_4.md
      - Lab 5: labs/lab_5.md
      - Lab 6: labs/lab_6.md
      - Lab 7: labs/lab_7.md
      - Lab 8: labs/lab_8.md
  - About me: author.md